nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization','Accept','Origin','X-Requested-With']

        # allow_credential: ['true']

        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': 
            allow_origin: ['*']
            allow_methods: ['POST', 'GET', 'DELETE']

        '^/api/': 
            allow_origin: ['*']
            allow_methods: ['POST', 'GET', 'DELETE']

